version: '3.8'

services:
  backend:
    build: ./
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - BREVO_API_KEY=suachave
      - SENDER_EMAIL=suporte@dominio.com
    networks:
      - chama-network

  frontend:
    build: ./frontend
    ports:
      - "5173:80"
    networks:
      - chama-network

networks:
  chama-network:
    driver: bridge
