services:
  chama-app:
    build: .
    container_name: chama-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB_HOST=host.docker.internal
      - DB_USER=seu_usuario
      - DB_PASS=sua_senha
      - DB_NAME=seu_banco
    volumes:
      - .:/app
    restart: unless-stopped
